version: '3'

services:
  country-app:
    image: bohdanbulakh/country-app
    container_name: country-app
    restart: unless-stopped
    depends_on:
      - postgres
      - watchtower
    ports:
      - "3003:3000"
    env_file:
      - ~/deployment/country-app/env/.country-app.dev.env

  postgres:
    image: postgres:16
    container_name: postgres-country-app
    restart: unless-stopped
    volumes:
      - ~/deployment/country-app/postgres/data:/var/lib/postgresql/data
    ports:
      - "8080:5432"
    env_file:
      - ~/deployment/country-app/env/.postgres.dev.env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-country-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--cleanup"
      - "-i"
      - "60"
